export const techsIcon = [
  {
    name: "html",
    src: "/html.png",
    alt: "HTML Icon",
    fullName: "HTML",
    show: true,
  },
  {
    name: "css",
    src: "/css.png",
    alt: "javaScript Icon",
    fullName: "CSS",
    show: true,
  },
  {
    name: "js",
    src: "/javascript.png",
    alt: "javaScript Icon",
    fullName: "JavaScript",
    show: true,
  },
  {
    name: "ts",
    src: "/typescript.png",
    alt: "typescript Icon",
    fullName: "TypeScript",
    show: true,
  },
  {
    name: "react",
    src: "/react.png",
    alt: "react Icon",
    fullName: "ReactJS",
    show: true,
  },
  {
    name: "php",
    src: "/php.png",
    alt: "php Icon",
    fullName: "php",
    show: true,
  },

  {
    name: "reactNative",
    src: "/react.png",
    alt: "reactNative Icon",
    fullName: "React Native",
    show: true,
  },
  {
    name: "node",
    src: "/nodejs.png",
    alt: "node Icon",
    fullName: "Node.js",
    show: true,
  },
  {
    name: "git",
    src: "/git.png",
    alt: "git Icon",
    fullName: "Git",
    show: true,
  },
  {
    name: "symfony",
    src: "/symfony.png",
    alt: "symfony Icon",
    fullName: "Symfony",
    show: true,
  },
  {
    name: "vue",
    src: "/vue.png",
    alt: "vue Icon",
    fullName: "Vue JS",
    show: true,
  },
  {
    name: "postgres",
    src: "/postgres.png",
    alt: "postgres Icon",
    fullName: "PostgreSQL",
    show: true,
  },
  {
    name: "linux",
    src: "/linux.png",
    alt: "Linux Icon",
    fullName: "Linux",
    show: true,
  },
  {
    name: "freebsd",
    src: "/freebsd.png",
    alt: "Freebsd Icon",
    fullName: "FreeBSD",
    show: false,
  },
  {
    name: "nextJs",
    src: "/nextjs.png",
    alt: "nextJs Icon",
    fullName: "Next.JS",
    show: false,
  },
  {
    name: "docker",
    src: "/docker.png",
    alt: "Docker Icon",
    fullName: "Docker",
    show: true,
  },
  {
    name: "tailwindcss",
    src: "/tailwind.png",
    alt: "TailwindCSS Icon",
    fullName: "TailwindCSS",
    show: true,
  },
];
